### PR TITLE
✨ Feature/team section

### PR DESCRIPTION
**Pull request by kesaralive**
## Summary
- Create a team section.
## Details
- Create a team section with team members.

## Checklist

- [x] Tested Changes
- [x] Stakeholder Approval
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.
- [x] I joined a screenshot of the app before and after the fix.

## Screenshots
screenshot-172 29 240 1_3000-2022 03 19-13_22_15

## Test Environments
- _Windows 10 Pro_
- _VSCode_
## Other Notes
(Add any additional information that would be useful to the developer or QA tester)

### CODE REVIEW

**Review by kesaralive — COMMENTED** [review]
double checked

**Comment by HasinduLanka** [comment]
Don't publish this with these images

**Comment by HasinduLanka** [comment]
Remove "Our team" section or replace those images with placeholders. I recommend the first option.

We should push this to production.

**Comment by BiGDoGKD** [comment]
@HasinduLanka team section is a very important part of this kind of website. It plays a major role to build trust among external actors. I suggest replacing images with placeholders for a small time till we take good photos.

**Pull request closed without merging**
