### PR TITLE
Production push

### PR DESCRIPTION
**Pull request by hariwij**
# Title (Replace this line)

Jira issue: [BMW-XXX](https://bitzquad.atlassian.net/browse/BMW-XXX)

## Checklist

-   [x] Meets the acceptance criteria
-   [ ] Tested all changes
-   [ ] Project builds with `npm run static`
-   [ ] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

### CODE REVIEW

**Review by geethakash — APPROVED** [review]
approved

**Review by HasinduLanka — CHANGES_REQUESTED** [review]
Do not add text content to pages directly. Add them to the Google sheet, `npm run text`, and import text from generated files.

**Comment by HasinduLanka** [comment]
Remember to fill in the pull request template

**Comment by HasinduLanka** [comment]
LGTM

**Review by HasinduLanka — APPROVED** [review]

**Pull request merged**
